# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Scale',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='board',
            new_name='scale',
        ),
    ]
